### ISSUE TITLE
Run duration not correctly reported

### ISSUE THREAD

**Issue by slagzter** [MicroFocus/alm-test-result-collection-tool#3]
Hello,
trying to report some runs from ALM.NET 12.60 to ALM Octane SaaS (12.60.47.88) I noticed that run duration is not correctly reported.
In ALM.NET we have a run with duration 248 **seconds** that in Octane is reported with 248 **milliseconds**.

Will this be fixed (for reporting and metrics purposes) in future releases?

My best regards,
Alberto

**Comment by radislavB** [comment]
Hi.
It will be fixed in next version.

**Comment by radislavB** [comment]
I hope in the beginning of next week, we will release fix.

**Comment by slagzter** [comment]
Perfect! Thanks Radislav!

Il ven 7 giu 2019, 07:52 Radislav Berkovich <notifications@github.com> ha
scritto:

**Comment by radislavB** [comment]
Hi.
New version is published [here](https://github.com/MicroFocus/alm-test-result-collection-tool/releases/tag/alm-test-result-collection-tool-1.0.10)

**Comment by slagzter** [comment]
Working, thanks!
