### ISSUE TITLE
latest release returning "A JSONObject text must begin with '{' at 1" message

### ISSUE THREAD

**Issue by agelop** [MicroFocus/alm-test-result-collection-tool#8]
Hello,

Latest tool release is returning the message "A JSONObject text must begin with '{' at 1" even with the simpler example file.
Please see the image below.

![image](https://user-images.githubusercontent.com/12619247/91883244-8cb36400-ec5a-11ea-8882-8891a903e410.png)

Could you help me?

Thanks,

Aldo

**Comment by radislavB** [comment]
hi, please send me example file to radislav.berkovich@microfocus.com

thanks
